Counties/Florida/Bay County/Makefile, Counties/Palm Beach County/Makefile
This will give us common way to execute scrapers and run tests between
languages. There's probably a better approach than this, but this is a
step up from consulting a README each time I want a scraper to Do The
Thing.
=> Add some Makefiles to run scrapers and tests.

Counties/Florida/Bay County/Scraper/Scraper.py
This isn't really needed for Bay County, but St. Johns county (which
also uses Benchmark) uses reCAPTCHA. This should make it easier to
integrate with St Johns county, at least, as well as other Benchmark
sources.
=> Allow humans to solve captchas.

.github/workflows/python-app.yml
=> Add more robust requirements.txt discovery

.github/workflows/python-app.yml
This should address the most-recent cause of test failure.
=> Install tesseract-ocr in CI env

Counties/Florida/Bay County/Scraper/Scraper.py, Counties/Florida/Bay County/Scraper/requirements.txt
It's more robust, does automatic validation, and automatically defines --help for us.
=> Move to absl for flag parsing

template/README.md
Strikethrough instead of deletion
=> Modify suggested action for collected fields

USA/IN/README.md
Found more info on state court data, there is a process to obtain that data the right way.
=> Added more info on IN data

README.md
- Adds updated dataset catalogue link
=> dataset catalogue → readme

README.md
We require that scrapers be reviewed to meet our [legal guidelines](https://pdap-docs.readthedocs.io/en/latest/volunteers/resources/legal_restrictions.html). Checking that scrapers comply with our legal requirements is top priority. **Approve working legal scrapers.**
1. Review the scraper for [legal risk](https://pdap-docs.readthedocs.io/en/latest/volunteers/resources/legal_restrictions.html). This is the most important approval criteria.
2. Does the sample data look sane and accurate? If so, approve it!
3. Make a comment if you have style suggestions. Better, share your skills by making a commit to their branch!
=> approval language

USA/NJ/README.md
Data from the state of New Jersey.
Scrape NJ court records at your own risk: we may not be able to use your data: https://njcourts.gov/courts/superior/eap.html
=> add NJ court restrictions to readme

USA/CA/burbank/README.md, USA/CA/burbank/configs.py, USA/CA/burbank/list_pdf_v2.py
=> Adds Burbank arrests scraper

template/README.md
=> Resolve scrapers template readme

Base_Scripts/etl/cityprotect/.gitignore, Base_Scripts/etl/cityprotect/cityprotect_load.py, common/etl/pdap_dolt.py
New etl scripts interface with both the `datasets` repo and the `data-intake` repo.
Currently, it will search for an agency & dataset, and add a new dataset if missing.
However, there are no checks on the `data-intake`, for now it just simply inserts all good data.
=> Upgraded ETL scripts

USA/CA/Brea/brea_annual_scraper.py
I had Stabs remove this from the prior PR and have it separated to be reviewed on the sites user policy found here:
https://www.ci.brea.ca.us/DocumentCenter/View/1329/Website-Content-User-Policy
=> CaptainStabs -/USA/CA/Brea Scraper

starter_template/schema_json_README.md
Update the readme on how the schema.json file works
=> Update schema.json readme

USA/AR/faulkner_county/conway/README.md, USA/AR/faulkner_county/conway/calls_for_service/items.py, USA/AR/faulkner_county/conway/calls_for_service/middlewares.py, USA/AR/faulkner_county/conway/calls_for_service/pipelines.py, USA/AR/faulkner_county/conway/calls_for_service/service_calls.json, USA/AR/faulkner_county/conway/calls_for_service/settings.py, USA/AR/faulkner_county/conway/calls_for_service/spiders/__init__.py, USA/AR/faulkner_county/conway/calls_for_service/spiders/conwaypd.py, USA/AR/faulkner_county/conway/etl.py, USA/AR/faulkner_county/conway/schema.json, USA/AR/faulkner_county/conway/scrapy.cfg, USA/AR/faulkner_county/conway/use_before_push.py
Added scraper for Conway Police Department in Conway, AR.
=> Added Conway, AR

starter_template/README.md
based on feedback with the Bounty Hunters
=> update template readme

Base_Scripts/Scrapers/list_pdf_extractors/list_pdf_readme.md, common/base_scrapers/crimegraphics/crimegraphics_arrest.py, common/base_scrapers/crimegraphics/crimegraphics_bulletin.py, common/base_scrapers/crimegraphics/crimegraphics_clery.py, common/base_scrapers/crimegraphics/utils/data_parser.py, common/base_scrapers/list_pdf_scrapers/list_pdf_v2.py, common/base_scrapers/list_pdf_scrapers/list_pdf_v3.py, common/base_scrapers/list_pdf_scrapers/single_pdf_scraper.py, common/base_scrapers/opendata/opendata_scraper_2.py, common/etl/data_extraction.py, common/utils/demo_utils/field_extractor.py, common/utils/demo_utils/truncate.py, common/utils/file_downloaders/downloaders.py, common/utils/list_pdf_utils/extract_info.py, common/utils/list_pdf_utils/get_files.py, common/utils/website_hasher/page_update.py
* Added docstrings to majority of functions
* Applied python black formatting to my scripts with line length 144 (looks better imho)
=> Added more documentation to my scripts

common/base_scrapers/list_pdf_scrapers/list_pdf_v3.py, common/utils/file_downloaders/downloaders.py, common/utils/list_pdf_utils/extract_info.py, common/utils/list_pdf_utils/get_files.py
* Added logging module to common files
* Updated if statements to use better practices
=> Updating stuff

common/ckan/package_list/main.py, common/ckan/package_list/readme.md, common/ckan/package_list/welcome.py
I'm writing a suite of tools that allows you to interface with a CKAN instance. This first tool "package_list" grabs all available data packages from a CKAN instance by only requiring the user to provide a "base" CKAN URL to the interactive command-line script. Still a work in progress; the next functionality is a script that allows the submission of data packages to a CKAN instance.
=> first commit of ckan tools and "package_list" tool

common/ckan/package_list/main.py
Added a comment to line 64 on about the debugging print() statement and what it's for
=> Updated comment for debugging statement on line 64

CONTRIBUTING.md
This still needs some love, but I wanted to fix the broken links and more obvious errors.
=> contributing link cleanup

CONTRIBUTING.md, README.md
=> update repo-cleanup from thejqs changes

utils/meta/open_data_network/README.md, utils/meta/open_data_network/open_data.py
* Small update so that instead of using a data sources CSV file to check for duplicates, it now gets the data from our API
=> Open Data Network scraper API integration

scrapers_library/GA/carroll_county/carrollton/carrollton_police/README.md, scrapers_library/data_portals/cityprotect/cityprotect.md, utils/pdf/list_pdf_scrapers/list_pdf_readme.md, utils/pdf/old_list_pdf_extractor/list_pdf.md, utils/sitemap_scraper/README.md
* Just a fix for some dead links in various README files that mostly pointed to an archived repository or old repo structure
=> Fix dead links

scrapers_library/CA/contra_costa_county/el_cerrito/el_cerrito_police/README.md, scrapers_library/CA/nevada_county/grass_valley/grass_valley_police/README.md, scrapers_library/CA/nevada_county/grass_valley/grass_valley_police/grass_valley_sb1421.py, utils/file_downloaders/downloaders.py
* Part of #206 
* Adds scraper for Grass Valley Police Department as part of SB 1421. Records being scraped can be found [here](https://www.cityofgrassvalley.com/records-release)
=> Grass Valley PD scraper

scrapers_library/CA/san_diego_county/la_mesa/la_mesa_police/README.md, scrapers_library/CA/san_diego_county/la_mesa/la_mesa_police/content.py, scrapers_library/CA/san_diego_county/la_mesa/la_mesa_police/la_mesa_sb1421.py
* Part of #206 
* La Mesa PD scraper for California's SB 1421
* Records being scraped can be found here: [https://www.cityoflamesa.us/1650/SB1421-Public-Records](https://www.cityoflamesa.us/1650/SB1421-Public-Records)
* Scraper requires at least 30 GB of available disk space and ~30 minutes to execute fully
=> La Mesa Scraper

utils/video/video_downloaders.py
* Adds two util functions for video downloading
* `youtube_downloader()` is for downloading YouTube videos
* `ts_downloader()` is for downloading and merging ts stream segments
=> Add video downloaders

CONTRIBUTING.md
=> contributing: fix data sources link

README.md, examples_templates/scraper_template/README.md, scrapers_library/PA/allegheny_county/departments_by_muni/README.md, scrapers_library/PA/allegheny_county/departments_by_muni/requirements.txt, scrapers_library/PA/allegheny_county/departments_by_muni/sample_no_police_departments.csv, scrapers_library/PA/allegheny_county/departments_by_muni/sample_police_departments.csv, scrapers_library/PA/allegheny_county/departments_by_muni/scraper.py
This came in handy for an Allegheny County research project
- none
- uses beautifulsoup to scrape, prettify, and CSV-ify departments, and areas without departments in a separate file.
- this level of prettification was enough for our purposes
- updates the main readme for accuracy, and the template readme because it was wildly out of date
- in the readme
=> allegheny departments by municipality scraper
